allowBuilds:
  core-js: true
  esbuild: true
  msw: true
  sharp: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - '@supabase/auth-js@2.110.7'
  - '@supabase/functions-js@2.110.7'
  - '@supabase/postgrest-js@2.110.7'
  - '@supabase/realtime-js@2.110.7'
  - '@supabase/storage-js@2.110.7'
  - '@supabase/supabase-js@2.110.7'
