-- ============================================================================
-- Sprint 16b: Thông báo — remaining notification triggers
-- AncestorTree v3.0.0
-- Covers: new_post, account_verified, new_member.
-- event_reminder is generated by /api/cron (date-window scan, not a trigger).
-- system is inserted via /api/notifications/broadcast (admin-only route).
-- ============================================================================

-- ─── Trigger: published post → notify verified members ──────────────────────

CREATE OR REPLACE FUNCTION notify_new_post()
RETURNS TRIGGER AS $$
BEGIN
    IF NEW.status != 'published' THEN
        RETURN NEW;
    END IF;

    INSERT INTO notifications (user_id, type, title, body, link, actor_id, reference_id)
    SELECT
        pr.user_id,
        'new_post',
        'Bài viết mới',
        COALESCE(
            (SELECT full_name FROM profiles WHERE user_id = NEW.author_id),
            'Thành viên'
        ) || ' đã đăng một bài viết mới',
        '/feed',
        NEW.author_id,
        NEW.id::text
    FROM profiles pr
    WHERE pr.is_verified = true
      AND pr.is_suspended = false
      AND pr.user_id != NEW.author_id;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public;

CREATE TRIGGER trg_notify_new_post
AFTER INSERT ON posts
FOR EACH ROW EXECUTE FUNCTION notify_new_post();

-- ─── Trigger: profile verified → notify that user ────────────────────────────

CREATE OR REPLACE FUNCTION notify_account_verified()
RETURNS TRIGGER AS $$
BEGIN
    IF NEW.is_verified = true AND OLD.is_verified IS DISTINCT FROM true THEN
        INSERT INTO notifications (user_id, type, title, body, link)
        VALUES (
            NEW.user_id,
            'account_verified',
            'Tài khoản đã được xác minh',
            'Tài khoản của bạn đã được quản trị viên xác minh. Bạn có thể sử dụng đầy đủ các tính năng của dòng họ.',
            '/settings'
        );
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public;

CREATE TRIGGER trg_notify_account_verified
AFTER UPDATE OF is_verified ON profiles
FOR EACH ROW EXECUTE FUNCTION notify_account_verified();

-- ─── Trigger: member registration → notify admins ────────────────────────────

CREATE OR REPLACE FUNCTION notify_new_member_registration()
RETURNS TRIGGER AS $$
BEGIN
    INSERT INTO notifications (user_id, type, title, body, link, reference_id)
    SELECT
        pr.user_id,
        'new_member',
        'Đơn đăng ký thành viên mới',
        NEW.full_name || ' vừa gửi đơn đăng ký gia nhập dòng họ',
        '/admin/registrations',
        NEW.id::text
    FROM profiles pr
    WHERE pr.role = 'admin'
      AND pr.is_suspended = false;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public;

CREATE TRIGGER trg_notify_new_member
AFTER INSERT ON member_registrations
FOR EACH ROW EXECUTE FUNCTION notify_new_member_registration();
